export const CHANGE_FACE_BOXES = 'CHANGE_FACE_BOXES';
export const UPDATE_USER_ENTRIES = 'UPDATE_USER_ENTRIES';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const GET_FACEDATA_SUCCESS = 'GET_FACEDATA_SUCCESS';
